# SPDX-License-Identifier: MPL-2.0

require "fileutils"
require_relative "builder"
require_relative "defines"
require_relative "update"
require_relative "utils"

module FelesBuild
  # dev の profile に user.js を置いて、版の控えを書く(build.rb dev-env)
  module DevEnvManager
    LOGGER = Utils::Logger.new("dev-env")

    USER_JS = <<~'JS'
      /**
       *! DO NOT EDIT THIS FILE.
       *
       ** This file is AUTOGENERATED
       ** Please modify the 'tools/lib/dev_env_manager.rb' in the repo.
       * https://github.com/nyanrus/noraneko
       */

      user_pref("devtools.debugger.prompt-connection",false);
      user_pref("security.disallow_privileged_https_script_loads", false);
      user_pref("security.allow_parent_unrestricted_js_loads", true);
      user_pref("remote.active-protocols", 1);
      user_pref("browser.newtabpage.enabled", true);
      user_pref("devtools.console.stdout.chrome", true);
      // drops(modules/Drops.sys.mts)= temporary add-on を privileged にする(experiment_apis と about: への注入)。
      // firefox.js の既定は false(Nightly/DevEdition だけ true)。製品の既定をどうするかは別途
      user_pref("extensions.experiments.enabled", true);
      // webext-actors(xpi + JSWindowActor。Firefox の about:newtab と同じ形)を使う。on のものは古い JSActor が外れる(BrowserGlue)
      user_pref("noraneko.webext-actors.newtab.enabled", true);
      user_pref("noraneko.webext-actors.about-preferences.enabled", true);
      user_pref("noraneko.webext-actors.settings-bridge.enabled", true);
    JS

    def self.save_prefs(profile_dir)
      FileUtils.mkdir_p(profile_dir)
      path = File.join(profile_dir, "user.js")
      File.write(path, USER_JS)
      LOGGER.success "user.js written to #{path}"
    rescue => e
      LOGGER.error "Failed to write user.js: #{e.message}"
    end

    def self.write_dev_version_info
      gecko = File.join(Defines::PROJECT_ROOT, "static", "gecko")
      dist = File.join(Defines::PROJECT_ROOT, "_dist")
      FileUtils.mkdir_p(dist)
      FileUtils.mkdir_p(File.join(gecko, "config"))

      File.write(File.join(gecko, "config", "version.txt"), "version: #{Builder.package_version}\n")
      buildid2 = Update.read_buildid2
      raise "buildid2 file not found at #{Defines::PATHS[:buildid2]}" if buildid2.nil?

      File.write(File.join(dist, "buildid2.txt"), "buildid2: #{buildid2}\n")
      LOGGER.success "Wrote dev version info."
    rescue => e
      LOGGER.error "Failed to write dev version info: #{e.message}"
    end

    def self.setup
      save_prefs(Defines::PATHS[:profile_test])
      write_dev_version_info
    end
  end
end
