# SPDX-License-Identifier: MPL-2.0

require "fileutils"
require "json"
require "tmpdir"
require_relative "defines"
require_relative "omni"
require_relative "utils"

module FelesBuild
  # runtime の binary を用意する。
  #
  # 取り先:
  # 1. NORANEKO_RUNTIME_TAG=passed-20260902074154 のように tag を指せば、GitHub release のその tag。
  # 2. 無ければ dl.f3liz.casa(noraneko-ci の産物、B2)。/latest/<target> が最新の sha へ 302 する。
  # 3. dl に無ければ GitHub release。**その資産を持つ一番新しい release を API で探す**
  #    ── 新しい platform は、揃うまで prerelease にしか無いことがある(`latest` は
  #    その platform を持たないまま古くなる)。見つからなければ latest に任せる。
  #
  # どこにも無い platform は、そこで止めて**何が無いのか**を言う。黙って 404 の
  # bytes を書いて、あとで tar が転ぶより、そのほうが分かる。
  module Initializer
    LOGGER = Utils::Logger.new("initializer")

    REPO = "f3liz-casa/noraneko-runtime"
    DL = "https://dl.f3liz.casa/noraneko-runtime"

    def self.release_url(tag, filename)
      "https://github.com/#{REPO}/releases/download/#{tag}/#{filename}"
    end

    def self.runtime_url(filename)
      tag = ENV["NORANEKO_RUNTIME_TAG"]
      return release_url(tag, filename) if tag && !tag.empty?

      from_dl(filename) || from_releases(filename) ||
        "https://github.com/#{REPO}/releases/latest/download/#{filename}"
    end

    # dl は /latest/<target> で最新の sha へ 302 する。行き先の URL をもらう。
    def self.from_dl(_filename)
      return nil unless %i[darwin linux].include?(Defines::PLATFORM)

      target = "#{Defines::PLATFORM == :darwin ? 'macos' : 'linux'}-#{Defines::ARCH}"
      result = Utils.run_checked("curl", "-sIL", "-o", File::NULL, "-w", "%{http_code} %{url_effective}",
                                 "#{DL}/latest/#{target}")
      code, url = result[:stdout].split
      return nil unless result[:success] && code == "200" && url

      # dl が返す名前は、いつも moz-artifact とは限らない(linux は package した
      # ほうの名前で置かれていることがある)。中の形は同じ(`<base_name>/…`)なので
      # そのまま使うけれど、**実際に取ったものの名前は出す**
      LOGGER.info "Runtime from dl.f3liz.casa: #{url}"
      url
    end

    # その資産を持つ、一番新しい release。platform が揃うまで prerelease にしか
    # 無いことがあるので、`latest` だけを見ない(darwin に限らず、どの platform も)。
    def self.from_releases(filename)
      result = Utils.run_checked("curl", "-sL", "-H", "accept: application/vnd.github+json",
                                 "https://api.github.com/repos/#{REPO}/releases?per_page=30")
      return nil unless result[:success]

      releases = JSON.parse(result[:stdout]) rescue nil
      hit = releases&.find { |r| r["assets"]&.any? { |a| a["name"] == filename } }
      unless hit
        LOGGER.warn "No release in the last 30 has #{filename} — " \
                    "this platform may not be built yet. See docs/DEV.md."
        return nil
      end

      published = hit["published_at"] ? " (#{hit['published_at'][0, 10]})" : ""
      LOGGER.info "Runtime release with #{filename}: #{hit['tag_name']}#{published}"
      release_url(hit["tag_name"], filename)
    end

    def self.run
      has_bin = File.exist?(Defines::BIN_PATH_EXE)
      has_version = File.exist?(Defines::BIN_VERSION)
      LOGGER.info Defines::BIN_VERSION

      need_init =
        if has_bin && has_version
          version = File.read(Defines::BIN_VERSION).strip
          if version == Defines::VERSION
            LOGGER.info "Binary version matches. No initialization needed."
            false
          else
            LOGGER.warn "Version mismatch: #{version} != #{Defines::VERSION}. Re-extracting."
            FileUtils.rm_rf(Defines::PATHS[:bin_root])
            true
          end
        elsif has_bin
          LOGGER.info "Binary exists but version file is missing. Writing #{Defines::VERSION}."
          FileUtils.mkdir_p(Defines::BIN_DIR)
          File.write(Defines::BIN_VERSION, Defines::VERSION)
          LOGGER.success "Initialization complete."
          false
        elsif has_version
          raise "Version file exists but binary is missing. Abnormal termination."
        else
          LOGGER.info "Binary not found. Extracting."
          true
        end

      if need_init
        FileUtils.mkdir_p(Defines::PATHS[:bin_root])
        decompress_bin
        LOGGER.success "Initialization complete."
      end

      save_prefs_for_profile
    end

    # このあと dev_env_manager が同じ user.js を書き直す(そちらが本命)。
    # Initializer だけを呼んだときに profile が空にならないように、ここにも置いてある。
    def self.save_prefs_for_profile
      dir = Defines::PATHS[:profile_test]
      FileUtils.mkdir_p(dir)
      File.write(File.join(dir, "user.js"), <<~JS)
        /**
         *! DO NOT EDIT THIS FILE.
         *
         ** This file is AUTOGENERATED
         ** Please modify the 'tools/lib/initializer.rb' in the repo.
         */
        user_pref("devtools.debugger.prompt-connection", false);
        user_pref("security.disallow_privileged_https_script_loads", false);
        user_pref("security.allow_parent_unrestricted_js_loads", true);
        user_pref("remote.active-protocols", 1);
        user_pref("browser.newtabpage.enabled", true);
      JS
      LOGGER.info "Wrote developer preferences to #{File.join(dir, 'user.js')}"
    end

    def self.download(filename, url)
      LOGGER.info "Downloading binary from #{url}"
      result = Utils.run_checked("curl", "-fL", "--progress-bar", "-w", "%{http_code}", "-o", filename, url)
      return LOGGER.success "Downloaded binary to #{filename}" if result[:success]

      # ここで止まるのは、たいてい「この platform の runtime が、まだどこにも
      # 置かれていない」とき。何が無いのかと、どうすれば進めるのかを言う。
      # (途中まで書けたものは消す。404 の bytes を残すと、あとで tar が転ぶ)
      File.delete(filename) if File.exist?(filename)
      raise <<~MESSAGE
        HTTP #{result[:stdout].strip} for #{url}
          #{filename} (#{Defines::PLATFORM}/#{Defines::ARCH}) がどこにも見つからない。
          持っている tag を指すなら: NORANEKO_RUNTIME_TAG=<tag> deno task feles-build dev
          置いてあるものの一覧: https://github.com/#{REPO}/releases
          どの platform が今あるのかは docs/DEV.md
      MESSAGE
    end

    def self.decompress_bin
      archive = Defines::STOCK_FIREFOX ? Defines.stock_archive : Defines.bin_archive
      filename = archive[:filename]

      # noraneko の道では、手元にある dmg は何でも使う(darwin)
      if !File.exist?(filename) && !Defines::STOCK_FIREFOX && Defines::PLATFORM == :darwin
        local = Dir.glob("*.dmg").first
        if local
          LOGGER.info "Found local DMG: #{local}. Using it."
          filename = local
          archive = archive.merge(format: :dmg)
        end
      end

      LOGGER.info "Binary extraction started: #{filename}#{Defines::STOCK_FIREFOX ? ' (stock Firefox)' : ''}"
      unless File.exist?(filename)
        LOGGER.warn "#{filename} not found. Downloading."
        download(filename, archive[:url] || runtime_url(filename))
      end

      Omni.discard # 新しい binary が来たら、ほどいた木は古い
      extract(File.expand_path(filename), archive[:format])
      File.write(Defines::BIN_VERSION, Defines::VERSION)
      LOGGER.success "Extraction complete!"
    end

    def self.extract(archive_path, format)
      case [Defines::PLATFORM, format]
      in [_, :zip] then extract_nested_zip(archive_path)
      in [:darwin, :tar_xz] then extract_mac_tar(archive_path)
      in [:darwin, :dmg] then extract_dmg(archive_path)
      in [:linux, :tar_xz]
        Utils.run("tar", "-xJf", archive_path, "-C", Defines::PATHS[:bin_root])
        Utils.run("chmod", "-R", "755", Defines::PATHS[:bin_root])
      else
        raise "Unsupported archive: #{Defines::PLATFORM} #{format}"
      end
    end

    # Windows の資産は zip の中に zip が入っている。
    def self.extract_nested_zip(archive_path)
      Dir.mktmpdir("nora-outer-", Defines.in_root("_dist")) do |tmp|
        LOGGER.info "Extracting outer zip..."
        unzip(archive_path, tmp)
        inner = Dir.glob(File.join(tmp, "*.zip")).first
        raise "No inner zip file found in the extracted archive" unless inner

        LOGGER.info "Extracting inner zip..."
        unzip(inner, Defines::PATHS[:bin_root])
      end
      Utils.run_checked("chmod", "-R", "755", Defines::PATHS[:bin_root]) if Defines::PLATFORM != :windows
    end

    def self.unzip(archive_path, into)
      return Utils.run("unzip", "-q", archive_path, "-d", into) if Defines::PLATFORM != :windows

      begin
        Utils.run("tar", "-xf", archive_path, "-C", into)
      rescue
        Utils.run("powershell", "-NoProfile", "-NonInteractive", "-Command",
                  "Expand-Archive -LiteralPath '#{archive_path}' -DestinationPath '#{into}' -Force")
      end
    end

    # aarch64 の .app は mach package(TAR)の staging: noraneko/Noraneko.app/…
    # linux と同じく bin_root に展開すると、狙った場所に落ちる。
    def self.extract_mac_tar(archive_path)
      LOGGER.info "macOS extraction (tar.xz)"
      dest = File.join(Defines::PATHS[:bin_root], Defines::BRANDING[:base_name])
      FileUtils.mkdir_p(dest)
      Utils.run("tar", "-xJf", archive_path, "-C", Defines::PATHS[:bin_root])
      clean_and_chmod(dest)
      # Linux で cross した bundle は無署名。Apple Silicon は署名が無いと dyld が libxul を
      # 拒む("Couldn't load XPCOM")ので ad-hoc で署名する。
      Utils.run("codesign", "--force", "--deep", "--sign", "-", Defines::APP_DIR)
    end

    def self.extract_dmg(archive_path)
      LOGGER.info "macOS extraction (hdiutil)"
      dest = File.join(Defines::PATHS[:bin_root], Defines::BRANDING[:base_name])
      FileUtils.mkdir_p(dest)
      mount = Dir.mktmpdir("nora_dmg_mount_")
      begin
        Utils.run("hdiutil", "attach", "-nobrowse", "-quiet", "-mountpoint", mount, archive_path)
        Utils.run("cp", "-a", "#{mount}/.", dest)
        clean_and_chmod(dest)
      ensure
        Utils.run_checked("hdiutil", "detach", "-quiet", mount)
        FileUtils.rmdir(mount) rescue nil
      end
    end

    def self.clean_and_chmod(dir)
      Utils.run_checked("xattr", "-rc", dir) # 無いこともある
      Utils.run("chmod", "-R", "755", dir)
    end

    # omni.ja を直したあとに、.app を結び直す。
    # 署名された bundle は omni.ja を触ると封が切れ、Apple Silicon は封の壊れた bundle を起動しない。
    # 「最後に omni.ja を触ったあと」= Omni.seal のあとに呼ぶこと。
    def self.resign_mac_app
      return unless Defines::PLATFORM == :darwin
      return unless Defines::STOCK_FIREFOX || Defines::ARCH == "aarch64"

      LOGGER.info "Ad-hoc re-signing #{Defines::APP_DIR} ..."
      Utils.run("codesign", "--force", "--deep", "--sign", "-", Defines::APP_DIR)
      Utils.run_checked("xattr", "-rc", Defines::APP_DIR)
      LOGGER.success "Ad-hoc re-sign complete."
    rescue => e
      LOGGER.warn "Re-sign failed (bundle may not launch on Apple Silicon): #{e.message}"
    end
  end
end
