// SPDX-License-Identifier: MPL-2.0

// Codegen + bundle orchestrator for actors.
//
// For each <name>/actor.ts it generates a small xpi into _dist/<name>/, shaped
// like Firefox's own about:newtab add-on: the xpi is only a container (manifest.json
// with id/version/hidden), and the page side is a JSWindowActor pair:
//   actor.json      registration options (name, matches, events, methods)
//   parent.sys.mjs  JSWindowActorParent: receiveMessage → parent[method](...args)
//   child.sys.mjs   JSWindowActorChild: loads content.js into the page's process
//   actor.mjs       parent methods (bundled by tsdown)
//   content.js      content hook + runtime (bundled by tsdown, IIFE)
// The .sys.mjs files reference resource://noraneko-builtin/<name>/; build-drop.rb
// rewrites that to the drop's own resource alias.
//
// The actor module's top level must be pure: this script imports it under Deno
// to read `meta` and the parent method names, so it must not touch Firefox
// globals (Services, ChromeUtils, window, ...) outside of method/hook bodies.

import * as path from "@std/path";

const ROOT = path.dirname(path.fromFileUrl(import.meta.url));
const DIST = path.join(ROOT, "_dist");
const GEN = path.join(ROOT, "_gen");

const mode =
  Deno.args
    .find((a) => a.startsWith("--env.MODE="))
    ?.slice("--env.MODE=".length) ?? "dev";

interface ActorMeta {
  id: string;
  version: string;
  namespace: string;
  matches: string[];
  runAt?: string;
  actor?: string;
  replaces?: string;
}

/** JSWindowActor name: meta.actor, or "Nora" + PascalCase(dir) (newtab → NoraNewtab, about-preferences → NoraAboutPreferences) */
function actorName(a: Actor): string {
  return a.meta.actor ?? "Nora" + a.dir.split(/[-_]/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

/** runAt → the child actor event that starts the content hook */
function runAtEvent(a: Actor): string {
  switch (a.meta.runAt ?? "document_end") {
    case "document_start": return "DOMDocElementInserted";
    case "document_idle": return "load";
    default: return "DOMContentLoaded";
  }
}

interface Actor {
  dir: string;
  meta: ActorMeta;
  methods: Array<{ name: string; arity: number }>;
}

function discoverActorDirs(): string[] {
  const dirs: string[] = [];
  for (const entry of Deno.readDirSync(ROOT)) {
    if (!entry.isDirectory) continue;
    if (entry.name.startsWith("_") || entry.name === "node_modules") continue;
    try {
      Deno.statSync(path.join(ROOT, entry.name, "actor.ts"));
      dirs.push(entry.name);
    } catch {
      // no actor.ts here
    }
  }
  return dirs.sort();
}

async function loadActor(dir: string): Promise<Actor> {
  const mod = await import(
    path.toFileUrl(path.join(ROOT, dir, "actor.ts")).href
  );
  const meta = mod.meta as ActorMeta;
  const parent = mod.parent as Record<string, (...a: unknown[]) => unknown>;
  const methods = Object.keys(parent).map((name) => ({
    name,
    arity: parent[name].length,
  }));
  return { dir, meta, methods };
}

function genManifest(a: Actor): string {
  // Container only (like newtab@mozilla.org): id / version / hidden. No content_scripts,
  // no experiment_apis, no background. Everything runs through the JSWindowActor pair.
  const manifest = {
    manifest_version: 2,
    name: a.dir,
    version: a.meta.version,
    browser_specific_settings: { gecko: { id: a.meta.id } },
    hidden: true,
  };
  return JSON.stringify(manifest, null, 2) + "\n";
}

/** Registration options + what a person can read before installing (methods, pages) */
function genActorJson(a: Actor): string {
  const web = a.meta.matches.some((m) => /^(\*|https?):\/\//.test(m));
  // the browser window itself (chrome://browser/content/browser.xhtml): the content hook then
  // runs inside that window, with gBrowser and everything else in reach
  const chrome = a.meta.matches.some((m) => m.startsWith("chrome://browser/"));
  const j = {
    name: actorName(a),
    id: a.meta.id,
    version: a.meta.version,
    matches: a.meta.matches,
    event: runAtEvent(a),
    methods: a.methods.map((m) => m.name),
    replaces: a.meta.replaces ?? null,
    // pages in the parent process (chrome://, about:preferences) and in every content process
    // (about:newtab lives in "privilegedabout"). Web pages only when a match says so (dev localhost).
    includeParent: true,
    includeChrome: chrome,
    safeForUntrustedWebProcess: web,
  };
  return JSON.stringify(j, null, 2) + "\n";
}

function genParentModule(a: Actor): string {
  const name = actorName(a);
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by build.ts. Edit ${a.dir}/actor.ts instead.
//
// JSWindowActorParent for ${name}: every sendQuery(method, args) from the child
// becomes parent[method](...args) in the main process (actor.mjs).

const METHODS = [${a.methods.map((m) => `"${m.name}"`).join(", ")}];

export class ${name}Parent extends JSWindowActorParent {
  async receiveMessage(message) {
    if (!METHODS.includes(message.name)) {
      throw new Error(\`${name}: unknown method \${message.name}\`);
    }
    const { parent } = ChromeUtils.importESModule(
      "resource://noraneko-builtin/${a.dir}/actor.mjs",
    );
    return parent[message.name](...(message.data ?? []));
  }
}
`;
}

function genChildModule(a: Actor): string {
  const name = actorName(a);
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by build.ts. Edit ${a.dir}/actor.ts instead.
//
// JSWindowActorChild for ${name}: on ${runAtEvent(a)} it loads content.js into this
// process with \`window\` / \`document\` / \`exportFunction\` / \`__nora\` on the scope
// chain (loadSubScript), so the content hook reads like a content script but runs
// with this actor's privileges. It is the same shape as Firefox's AboutNewTabChild.

export class ${name}Child extends JSWindowActorChild {
  #ran = false;
  #onDestroy = [];

  handleEvent(event) {
    if (event.type !== "${runAtEvent(a)}" || this.#ran) return;
    this.#ran = true;
    const win = this.contentWindow;
    if (!win) return;
    const actor = this;
    const scope = {
      window: win,
      document: win.document,
      exportFunction: (fn, target, options) => Cu.exportFunction(fn, target, options),
      __nora: {
        call: (method, args) => actor.sendQuery(method, args),
        expose(funcs) {
          for (const [n, fn] of Object.entries(funcs)) {
            Cu.exportFunction(fn, win, { defineAs: n });
          }
        },
        onDestroy: (fn) => actor.#onDestroy.push(fn),
      },
    };
    try {
      Services.scriptloader.loadSubScript(
        "resource://noraneko-builtin/${a.dir}/content.js",
        scope,
      );
    } catch (e) {
      console.error("[${name}] content.js failed:", e);
    }
  }

  // The actor was unregistered (drop removed or replaced) or the window is going
  // away: give the content hook its chance to put things back. Last placed,
  // first taken out (a view is unmounted before the box it was mounted in goes).
  didDestroy() {
    for (const fn of this.#onDestroy.splice(0).reverse()) {
      try {
        fn();
      } catch (e) {
        console.error("[${name}] cleanup failed:", e);
      }
    }
  }
}
`;
}

function genContentEntry(a: Actor): string {
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by build.ts.
import { content, meta } from "../../${a.dir}/actor.ts";
import { runContent } from "../../_shared/contentRuntime.ts";
runContent(meta, content);
`;
}

// Re-export only `parent` so the parent bundle tree-shakes out the content hook
// (and birpc): none of that should ship in the main-process module.
function genParentEntry(a: Actor): string {
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by build.ts.
export { parent } from "../../${a.dir}/actor.ts";
`;
}

/** What one actor's xpi contains (besides source/, which build-drop.rb adds) */
export const ACTOR_FILES = [
  "manifest.json",
  "actor.json",
  "parent.sys.mjs",
  "child.sys.mjs",
  "actor.mjs",
  "content.js",
];

function genJarMn(actors: Actor[]): string {
  const header =
    "noraneko.jar:\n% resource noraneko-builtin %nora-builtin/ contentaccessible=yes";
  const files = actors.flatMap((a) =>
    ACTOR_FILES.map((f) => `nora-builtin/${a.dir}/${f} (${a.dir}/${f})`),
  );
  files.push("nora-builtin/builtins.json (builtins.json)");
  return `${header}\n ${files.join("\n ")}\n`;
}

async function runTsdown(config: string, actorDir: string): Promise<void> {
  const cmd = new Deno.Command("deno", {
    args: ["run", "-A", "npm:tsdown", "-c", config, `--env.MODE=${mode}`],
    cwd: ROOT,
    env: { WEBEXT_ACTOR: actorDir },
    stdout: "inherit",
    stderr: "inherit",
  });
  const { code } = await cmd.output();
  if (code !== 0) {
    throw new Error(`tsdown failed for ${config} (${actorDir})`);
  }
}

// --- main ---

const actorDirs = discoverActorDirs();
const actors = await Promise.all(actorDirs.map(loadActor));

await Deno.remove(DIST, { recursive: true }).catch(() => {});
await Deno.remove(GEN, { recursive: true }).catch(() => {});

const builtins = [];
for (const a of actors) {
  const outDir = path.join(DIST, a.dir);
  Deno.mkdirSync(outDir, { recursive: true });
  Deno.writeTextFileSync(path.join(outDir, "manifest.json"), genManifest(a));
  Deno.writeTextFileSync(path.join(outDir, "actor.json"), genActorJson(a));
  Deno.writeTextFileSync(path.join(outDir, "parent.sys.mjs"), genParentModule(a));
  Deno.writeTextFileSync(path.join(outDir, "child.sys.mjs"), genChildModule(a));

  const genDir = path.join(GEN, a.dir);
  Deno.mkdirSync(genDir, { recursive: true });
  Deno.writeTextFileSync(
    path.join(genDir, "content.entry.ts"),
    genContentEntry(a),
  );
  Deno.writeTextFileSync(
    path.join(genDir, "parent.entry.ts"),
    genParentEntry(a),
  );

  builtins.push({
    id: a.meta.id,
    version: a.meta.version,
    pref: `noraneko.webext-actors.${a.dir}.enabled`,
    res_url: `resource://noraneko-builtin/${a.dir}/`,
    actor: JSON.parse(genActorJson(a)),
  });
}

Deno.writeTextFileSync(
  path.join(DIST, "builtins.json"),
  JSON.stringify(builtins, null, 2) + "\n",
);
Deno.writeTextFileSync(path.join(DIST, "jar.mn"), genJarMn(actors));
Deno.writeTextFileSync(
  path.join(DIST, "moz.build"),
  `JAR_MANIFESTS += ["jar.mn"]\n`,
);

console.log(
  `[webext-actors] generated ${actors.length} actor(s): ${actorDirs.join(", ")}`,
);

for (const a of actors) {
  await runTsdown("tsdown.actor.config.ts", a.dir);
  await runTsdown("tsdown.content.config.ts", a.dir);
}

console.log("[webext-actors] build complete.");
