// SPDX-License-Identifier: MPL-2.0

import * as path from "@std/path";
import {
  PLATFORM,
  VERSION,
  BRANDING,
  PATHS,
  APP_DIR,
  BIN_DIR,
  BIN_ROOT_DIR,
  BIN_PATH_EXE,
  BIN_VERSION,
  STOCK_FIREFOX,
  getBinArchive,
  getStockArchive,
} from "./defines.ts";
import { Logger, runCommand, exists, safeRemove } from "./utils.ts";

// NORANEKO_RUNTIME_TAG=passed-20260902074154 のように tag を指すと prerelease も飲める。
// 未指定なら latest(prerelease は含まれない)。
const NORANEKO_RUNTIME_TAG = Deno.env.get("NORANEKO_RUNTIME_TAG");
const NORANEKO_RUNTIME_BASE = NORANEKO_RUNTIME_TAG
  ? `https://github.com/f3liz-casa/noraneko-runtime/releases/download/${NORANEKO_RUNTIME_TAG}`
  : "https://github.com/f3liz-casa/noraneko-runtime/releases/latest/download";

const logger = new Logger("initializer");

/**
 * Entry point: ensure binary is present and preferences saved.
 */
export async function run(): Promise<void> {
  const hasVersion = exists(BIN_VERSION);
  const hasBin = exists(BIN_PATH_EXE);
  let needInit = false;

  logger.info(BIN_VERSION);

  if (hasBin && hasVersion) {
    const version = Deno.readTextFileSync(BIN_VERSION).trim();
    if (VERSION !== version) {
      logger.warn(
        `Version mismatch: ${version} !== ${VERSION}. Re-extracting.`,
      );
      safeRemove(BIN_ROOT_DIR);
      needInit = true;
    } else {
      logger.info("Binary version matches. No initialization needed.");
    }
  } else if (hasBin && !hasVersion) {
    logger.info(
      `Binary exists but version file is missing. Writing ${VERSION}.`,
    );
    Deno.mkdirSync(BIN_DIR, { recursive: true });
    Deno.writeTextFileSync(BIN_VERSION, VERSION);
    logger.success("Initialization complete.");
  } else if (!hasBin && hasVersion) {
    logger.error(
      "Version file exists but binary is missing. Abnormal termination.",
    );
    throw new Error("Unreachable: !has_bin && has_version");
  } else {
    logger.info("Binary not found. Extracting.");
    needInit = true;
  }

  if (needInit) {
    Deno.mkdirSync(BIN_ROOT_DIR, { recursive: true });
    await decompressBin();
    logger.success("Initialization complete.");
  }

  savePrefsForProfile();
}

export function savePrefsForProfile(): void {
  const profileDir = PATHS.profile_test;
  const userJsPath = path.join(profileDir, "user.js");

  const userJsContent = `/**
 *! DO NOT EDIT THIS FILE.
 *
 ** This file is AUTOGENERATED
 ** Please modify the 'tools/lib/initializer.rb' in the repo.
 */
user_pref("devtools.debugger.prompt-connection", false);
user_pref("security.disallow_privileged_https_script_loads", false);
user_pref("security.allow_parent_unrestricted_js_loads", true);
user_pref("remote.active-protocols", 1);
user_pref("browser.newtabpage.enabled", true);
`;

  Deno.mkdirSync(profileDir, { recursive: true });
  Deno.writeTextFileSync(userJsPath, userJsContent);
  logger.info(`Wrote developer preferences to ${userJsPath}`);
}

async function extractNestedZip(
  outerZipPath: string,
  extractToDir: string,
): Promise<void> {
  const tempDir = "_dist/temp_extract_" + Date.now();
  await Deno.mkdir(tempDir);

  try {
    logger.info("Extracting outer zip...");

    // Extract outer zip to temp directory
    switch (PLATFORM) {
      case "windows":
        try {
          runCommand("tar", ["-xf", outerZipPath, "-C", tempDir]);
        } catch {
          runCommand("powershell", [
            "-NoProfile",
            "-NonInteractive",
            "-Command",
            `Expand-Archive -LiteralPath '${outerZipPath}' -DestinationPath '${tempDir}' -Force`,
          ]);
        }
        break;
      case "darwin":
      case "linux":
        runCommand("unzip", ["-q", outerZipPath, "-d", tempDir]);
        break;
    }

    // Find the inner zip file
    let innerZipPath: string | null = null;
    for (const entry of Deno.readDirSync(tempDir)) {
      if (entry.name.endsWith(".zip")) {
        innerZipPath = path.join(tempDir, entry.name);
        break;
      }
    }

    if (!innerZipPath) {
      throw new Error("No inner zip file found in the extracted archive");
    }

    logger.info("Extracting inner zip...");

    // Extract inner zip to final destination
    switch (PLATFORM) {
      case "windows":
        try {
          runCommand("tar", ["-xf", innerZipPath, "-C", extractToDir]);
        } catch {
          runCommand("powershell", [
            "-NoProfile",
            "-NonInteractive",
            "-Command",
            `Expand-Archive -LiteralPath '${innerZipPath}' -DestinationPath '${extractToDir}' -Force`,
          ]);
        }
        break;
      case "darwin":
      case "linux":
        runCommand("unzip", ["-q", innerZipPath, "-d", extractToDir]);
        break;
    }

    // Set proper permissions on Unix-like systems
    if (PLATFORM !== "windows") {
      try {
        runCommand("chmod", ["-R", "755", extractToDir]);
      } catch {
        // Ignore chmod errors
      }
    }
  } finally {
    // Clean up temp directory
    try {
      Deno.removeSync(tempDir, { recursive: true });
    } catch {
      // Ignore cleanup errors
    }
  }
}

export async function decompressBin(): Promise<void> {
  const binArchive = STOCK_FIREFOX ? getStockArchive() : getBinArchive();
  const downloadUrl = STOCK_FIREFOX
    ? (binArchive as { url: string }).url
    : `${NORANEKO_RUNTIME_BASE}/${binArchive.filename}`;
  logger.info(
    `Binary extraction started: ${binArchive.filename}` +
      (STOCK_FIREFOX ? " (stock Firefox)" : ""),
  );

  if (!exists(binArchive.filename)) {
    // For the noraneko-runtime path, accept any local DMG on darwin.
    if (!STOCK_FIREFOX && PLATFORM === "darwin") {
      for (const entry of Deno.readDirSync(PATHS.root)) {
        if (entry.isFile && entry.name.endsWith(".dmg")) {
          logger.info(`Found local DMG: ${entry.name}. Using it.`);
          binArchive.filename = entry.name;
          break;
        }
      }
    }

    if (!exists(binArchive.filename)) {
      logger.warn(`${binArchive.filename} not found. Downloading.`);
      await downloadBin(binArchive.filename, downloadUrl);
    }
  }

  const archivePath = path.resolve(binArchive.filename);

  try {
    // Handle nested zip extraction
    if (binArchive.filename.endsWith(".zip")) {
      await extractNestedZip(archivePath, BIN_ROOT_DIR);
    } else {
      // Handle other archive formats (DMG, tar.xz, etc.)
      switch (PLATFORM) {
        case "windows":
          throw new Error("Non-zip archives not supported on Windows");

        case "darwin": {
          const destDir = path.join(BIN_ROOT_DIR, BRANDING.base_name);
          Deno.mkdirSync(destDir, { recursive: true });
          if (archivePath.endsWith(".tar.xz")) {
            // aarch64 の .app が tar.xz で来る(中身は Noraneko.app/ 一つ)
            logger.info("macOS extraction (tar.xz)");
            runCommand("tar", ["-xJf", archivePath, "-C", destDir]);
            try {
              runCommand("xattr", ["-rc", destDir]);
            } catch {
              // xattr might not be present; ignore
            }
            runCommand("chmod", ["-R", "755", destDir]);
            break;
          }
          logger.info("macOS extraction (hdiutil)");
          const mountPoint = await Deno.makeTempDir({
            prefix: "nora_dmg_mount_",
          });
          try {
            runCommand("hdiutil", [
              "attach",
              "-nobrowse",
              "-quiet",
              "-mountpoint",
              mountPoint,
              archivePath,
            ]);
            runCommand("cp", ["-a", `${mountPoint}/.`, destDir]);
            try {
              runCommand("xattr", ["-rc", destDir]);
            } catch {
              // xattr might not be present; ignore
            }
            runCommand("chmod", ["-R", "755", destDir]);
          } finally {
            try {
              runCommand("hdiutil", ["detach", "-quiet", mountPoint]);
            } catch {
              // ignore detach failures
            }
          }
          break;
        }

        case "linux": {
          runCommand("tar", ["-xJf", archivePath, "-C", BIN_ROOT_DIR]);
          runCommand("chmod", ["-R", "755", BIN_ROOT_DIR]);
          break;
        }

        default:
          throw new Error(`Unsupported platform: ${PLATFORM}`);
      }
    }

    if (STOCK_FIREFOX) {
      deoptimizeOmni(path.join(BIN_DIR, "browser", "omni.ja"));
    }

    Deno.writeTextFileSync(BIN_VERSION, VERSION);
    logger.success("Extraction complete!");
  } catch (e: any) {
    logger.error(`Error during extraction: ${e?.message ?? e}`);
    Deno.exit(1);
  }
}

/**
 * Stock Firefox ships an "optimized" omni.ja (central directory relocated for
 * faster startup), which JSZip — used by the patcher/injector — can't read
 * ("expected N records in central dir, got 0"). System unzip can read it, so we
 * extract and repack as a standard STORE zip. Firefox loads a standard omni.ja
 * fine (unoptimized builds ship one); this just makes it JSZip-editable.
 */
function deoptimizeOmni(omniPath: string): void {
  if (!exists(omniPath)) {
    logger.warn(`omni.ja not found for deoptimize: ${omniPath}`);
    return;
  }
  logger.info(`Deoptimizing ${omniPath} (repack as standard zip)...`);
  const tmpDir = `${omniPath}.unpacked`;
  try {
    safeRemove(tmpDir);
  } catch {
    // ignore
  }
  Deno.mkdirSync(tmpDir, { recursive: true });

  // unzip exits non-zero on the "extra bytes" warning but still extracts.
  new Deno.Command("unzip", {
    args: ["-q", "-o", omniPath, "-d", tmpDir],
    stdout: "null",
    stderr: "null",
  }).outputSync();

  if (!exists(path.join(tmpDir, "modules"))) {
    throw new Error(`Deoptimize failed: unzip did not extract ${omniPath}`);
  }

  Deno.removeSync(omniPath);

  // Repack as a standard, uncompressed (STORE) zip with the same layout.
  const zipRes = new Deno.Command("zip", {
    args: ["-0", "-q", "-r", "-X", omniPath, "."],
    cwd: tmpDir,
    stdout: "null",
    stderr: "piped",
  }).outputSync();
  if (zipRes.code !== 0) {
    throw new Error(
      `Deoptimize failed: zip exited ${zipRes.code}: ${new TextDecoder().decode(zipRes.stderr)}`,
    );
  }

  try {
    safeRemove(tmpDir);
  } catch {
    // ignore
  }
  logger.success("omni.ja deoptimized (standard zip).");
}

export async function downloadBin(filename: string, url?: string): Promise<void> {
  const downloadUrl = url ?? `${NORANEKO_RUNTIME_BASE}/${filename}`;
  logger.info(`Downloading binary from ${downloadUrl}`);

  const resp = await fetch(downloadUrl);
  if (!resp.ok) {
    throw new Error(`HTTP error ${resp.status}`);
  }
  const data = new Uint8Array(await resp.arrayBuffer());
  await Deno.writeFile(filename, data);

  logger.success(`Downloaded binary to ${filename}`);
}

/**
 * Ad-hoc re-sign the app bundle on darwin after omni.ja was modified.
 * Stock Firefox.app is signed/notarized; editing omni.ja breaks that seal and
 * arm64 refuses to launch an invalidly-signed bundle. `codesign --force --deep
 * --sign -` re-seals the (modified) bundle with an ad-hoc signature, so it must
 * run after the last bundle modification (patcher + injector + xhtml).
 * No-op unless darwin + STOCK_FIREFOX.
 */
export function resignMacApp(): void {
  if (PLATFORM !== "darwin" || !STOCK_FIREFOX) {
    return;
  }
  logger.info(`Ad-hoc re-signing ${APP_DIR} ...`);
  try {
    runCommand("codesign", ["--force", "--deep", "--sign", "-", APP_DIR]);
    try {
      runCommand("xattr", ["-rc", APP_DIR]);
    } catch {
      // quarantine attr may be absent; ignore
    }
    logger.success("Ad-hoc re-sign complete.");
  } catch (e: any) {
    logger.warn(
      `Re-sign failed (bundle may not launch on Apple Silicon): ${e?.message ?? e}`,
    );
  }
}
