// SPDX-License-Identifier: MPL-2.0



/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

export const env = Services.env;
export const isMainBrowser = env.get("MOZ_BROWSER_TOOLBOX_PORT") === "";

const executedFunctions = new Set<string>();

export function executeOnce(id: string, callback: () => void): boolean {
  if (executedFunctions.has(id)) {
    return false;
  }

  callback();

  executedFunctions.add(id);
  return true;
}

export function onFinalUIStartup(): void {
  Services.obs.removeObserver(onFinalUIStartup, "final-ui-startup");

  createDefaultUserChromeFiles().catch((error) => {
    console.error("Failed to create default userChrome files:", error);
  });

  registerBuiltinWebExtActors().catch((error) => {
    console.error("Failed to register builtin WebExtension actors:", error);
  });
  // NORANEKO_DROP_CODE=<code> で起動すると、その drop を入れる(dev と試験のため。Drops.sys.mts)
  ChromeUtils.importESModule("resource://noraneko/modules/Drops.sys.mjs")
    .maybeInstallDropFromEnv()
    .catch((error: unknown) => {
      console.error("[noraneko-drops] startup install failed:", error);
    });
}

/**
 * Parallel mechanism to JSActors: register noraneko's privileged built-in
 * WebExtensions. Built-in addons are automatically privileged, which lets them
 * declare experiment_apis (main-process code) and match restricted schemes.
 *
 * The list is generated by the webext-actors build (resource://noraneko-builtin/
 * builtins.json). Each entry is gated behind its own pref so it stays opt-in
 * while the JSActor versions remain.
 *
 * This runtime install is the fallback path (flat dev layout). In the omni
 * layout the injector adds these to built_in_addons.json at build time, matching
 * upstream and avoiding the about:newtab startup race; maybeInstallBuiltinAddon
 * is idempotent, so calling it again here is harmless.
 */
interface BuiltinActorEntry {
  id: string;
  version: string;
  pref: string;
  res_url: string;
}

async function registerBuiltinWebExtActors(): Promise<void> {
  let entries: BuiltinActorEntry[];
  try {
    const response = await fetch("resource://noraneko-builtin/builtins.json");
    if (!response.ok) {
      return;
    }
    entries = await response.json();
  } catch (error) {
    console.error("[noraneko] Failed to read builtins.json:", error);
    return;
  }

  const enabled = entries.filter((entry) =>
    Services.prefs.getBoolPref(entry.pref, false),
  );
  if (enabled.length === 0) {
    return;
  }

  const { AddonManager } = ChromeUtils.importESModule(
    "resource://gre/modules/AddonManager.sys.mjs",
  );

  for (const entry of enabled) {
    try {
      await AddonManager.maybeInstallBuiltinAddon(
        entry.id,
        entry.version,
        entry.res_url,
      );
    } catch (error) {
      console.error(`Failed to install builtin addon ${entry.id}:`, error);
    }
  }
}

async function createDefaultUserChromeFiles(): Promise<void> {
  const chromeDir = PathUtils.join(
    Services.dirsvc.get("ProfD", Ci.nsIFile).path,
    "chrome",
  );
  const chromeExists = await IOUtils.exists(chromeDir);

  if (!chromeExists) {
    const userChromeCssPath = PathUtils.join(chromeDir, "userChrome.css");
    const userContentCssPath = PathUtils.join(chromeDir, "userContent.css");

    await IOUtils.writeUTF8(
      userChromeCssPath,
      `
/*************************************************************************************************************************************************************************************************************************************************************

"userChrome.css" is a custom CSS file that can be used to specify CSS style rules for Floorp's interface (NOT internal site) using "chrome" privileges.
For instance, if you want to hide the tab bar, you can use the following CSS rule:

**************************************
#TabsToolbar {                       *
    display: none !important;        *
}                                    *
**************************************

NOTE: You can use the userChrome.css file without change preferences (about:config)

Quote: https://userChrome.org | https://github.com/topics/userchrome 

************************************************************************************************************************************************************************************************************************************************************/

@charset "UTF-8";
@-moz-document url(chrome://browser/content/browser.xhtml) {
/* Please write your custom CSS under this line*/


}
`,
    );

    await IOUtils.writeUTF8(
      userContentCssPath,
      `
/*************************************************************************************************************************************************************************************************************************************************************

"userContent.css" is a custom CSS file that can be used to specify CSS style rules for Floorp's internal site using "chrome" privileges.
For instance, if you want to apply CSS at "about:newtab" and "about:home", you can use the following CSS rule:

***********************************************************************
@-moz-document url-prefix("about:newtab"), url-prefix("about:home") { *
                                                                      *
* Write your css *                                                    *
                                                                      *
}                                                                     *
***********************************************************************

NOTE: You can use the userContent.css file without change preferences (about:config)

************************************************************************************************************************************************************************************************************************************************************/

@charset "UTF-8";
/* Please write your custom CSS under this line*/
`,
    );
  }
}

// Only for dev build
async function setupNoranekoNewTab(): Promise<void> {
  const { AboutNewTab } = ChromeUtils.importESModule(
    "resource:///modules/AboutNewTab.sys.mjs",
  );

  if ((await isNewTabFileAvailable()) === false) {
    // Fallback for dev build about:newtab if file doesn't exist
    AboutNewTab.newTabURL = "http://localhost:5186/";
  }
}

async function isNewTabFileAvailable(): Promise<boolean> {
  try {
    const response = await fetch("chrome://noraneko-newtab/content/index.html");
    return response.ok;
  } catch (error) {
    console.error("[noraneko] Failed to check newtab file:", error);
    return false;
  }
}

async function checkNewtabUserPreference(): Promise<boolean> {
  if ((await isNewTabFileAvailable()) === false) {
    return false;
  }

  return true;
}

/* Register Custom About Pages
 *
 * Credits: angelbruni/Geckium on GitHub
 * This code is the TypeScript version of the original JavaScript code.
 *
 * File referred: https://github.com/angelbruni/Geckium/blob/main/Profile%20Folder/chrome/JS/Geckium_aboutPageRegisterer.uc.js
 */

const getCustomAboutPages = async (): Promise<Record<string, string>> => {
  const customAboutPages: Record<string, string> = {
    hub: "chrome://noraneko-settings/content/index.html",
    welcome: "chrome://noraneko-welcome/content/index.html",
    // about-module names may contain a colon (NS_GetAboutModuleName only
    // strips at #/?), so "about:nora:settings" keeps the nora: branding while
    // going through about:'s fully-supported load path (a raw nora: scheme is
    // blocked by content security; see firefox-custom-url-scheme memo).
    "nora:settings": "chrome://noraneko-settings/content/index.html",
  };

  if (await checkNewtabUserPreference()) {
    customAboutPages["newtab"] = "chrome://noraneko-newtab/content/index.html";
    customAboutPages["home"] = "chrome://noraneko-newtab/content/index.html";
  }

  return customAboutPages;
};

class CustomAboutPage {
  private _uri: nsIURI;

  constructor(urlString: string) {
    this._uri = Services.io.newURI(urlString);
  }

  get uri(): nsIURI {
    return this._uri;
  }

  newChannel(_uri: nsIURI, loadInfo: nsILoadInfo): nsIChannel {
    const new_ch = Services.io.newChannelFromURIWithLoadInfo(
      this.uri,
      loadInfo,
    );
    new_ch.owner = Services.scriptSecurityManager.getSystemPrincipal();
    return new_ch;
  }

  getURIFlags(_uri: nsIURI): number {
    return (
      Ci.nsIAboutModule.ALLOW_SCRIPT! | Ci.nsIAboutModule.IS_SECURE_CHROME_UI!
    );
  }

  getChromeURI(_uri: nsIURI): nsIURI {
    return this.uri;
  }

  QueryInterface = ChromeUtils.generateQI(["nsIAboutModule"]);
}

async function registerCustomAboutPages(): Promise<void> {
  const customAboutPages = await getCustomAboutPages();

  for (const aboutKey in customAboutPages) {
    const AboutModuleFactory: nsIFactory = {
      createInstance(aIID: nsIID): any {
        return new CustomAboutPage(customAboutPages[aboutKey]).QueryInterface(
          aIID,
        );
      },
    };

    const registrar = Components.manager.QueryInterface!(
      Ci.nsIComponentRegistrar,
    );
    if (!registrar) {
      console.error("Failed to get nsIComponentRegistrar");
      continue;
    }
    registrar.registerFactory(
      Services.uuid.generateUUID(),
      `about:${aboutKey}`,
      `@mozilla.org/network/protocol/about;1?what=${aboutKey}`,
      AboutModuleFactory,
    );
  }
}

(async () => {
  await setupNoranekoNewTab();
})().catch(console.error);
registerCustomAboutPages();

if (isMainBrowser) {
  Services.obs.addObserver(onFinalUIStartup, "final-ui-startup");
}
