// SPDX-License-Identifier: MPL-2.0
// 色と形。ページ一枚ぶんなので CSS file を持たず、inline style のまま

export const color = {
  text: "#1a1d24",
  muted: "#6a7180",
  accent: "#5b8def",
  line: "#e6e9f0",
  lineSoft: "#eef0f5",
  codeText: "#45506a",
  codeBg: "#f0f3fa",
  okText: "#1c7a43",
  okBg: "#e3f4e9",
  warnText: "#9a5b13",
  warnBg: "#fdeede",
  ngText: "#b3261e",
  dangerText: "#8c1d18",
  dangerBg: "#fdeaea",
  dangerLine: "#f2b8b5",
};

export const s = {
  main: {
    fontFamily: "system-ui, sans-serif",
    maxWidth: "44rem",
    margin: "0 auto",
    padding: "2.5rem 1.5rem 4rem",
    color: color.text,
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    flexWrap: "wrap" as const,
    marginBottom: "1.5rem",
  },
  h1: { color: color.accent, margin: 0, fontSize: "1.7rem" },
  badge: (ok: boolean) => ({
    fontSize: "0.75rem",
    padding: "0.2rem 0.55rem",
    borderRadius: "999px",
    fontWeight: 600,
    background: ok ? color.okBg : color.warnBg,
    color: ok ? color.okText : color.warnText,
  }),
  section: {
    background: "#fff",
    border: `1px solid ${color.line}`,
    borderRadius: "0.75rem",
    padding: "1.25rem 1.4rem",
    marginTop: "1.25rem",
  },
  h2: { margin: "0 0 0.25rem", fontSize: "1.05rem" },
  hint: { margin: "0 0 1rem", color: color.muted, fontSize: "0.85rem" },
  row: {
    display: "flex",
    gap: "0.8rem",
    padding: "0.7rem 0",
    borderTop: `1px solid ${color.lineSoft}`,
  },
  rowText: { display: "flex", flexDirection: "column" as const, gap: "0.2rem" },
  label: { fontWeight: 600 },
  desc: { color: color.muted, fontSize: "0.85rem" },
  code: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "0.78rem",
    color: color.codeText,
    background: color.codeBg,
    padding: "0.1rem 0.35rem",
    borderRadius: "0.3rem",
    alignSelf: "flex-start" as const,
  },
  pre: {
    fontFamily: "ui-monospace, monospace",
    fontSize: "0.78rem",
    color: color.codeText,
    background: color.codeBg,
    borderRadius: "0.3rem",
    whiteSpace: "pre-wrap" as const,
    maxHeight: "24rem",
    overflow: "auto",
    padding: "0.6rem",
  },
  input: { flex: 1, padding: "0.4rem 0.6rem", border: `1px solid ${color.line}`, borderRadius: "0.4rem" },
  actions: { display: "flex", gap: "0.5rem", marginTop: "0.6rem" },
  danger: {
    marginTop: "0.8rem",
    padding: "0.7rem 0.9rem",
    borderRadius: "0.5rem",
    background: color.dangerBg,
    border: `1px solid ${color.dangerLine}`,
    color: color.dangerText,
    fontSize: "0.9rem",
  },
  dangerButton: { borderColor: color.ngText, color: color.dangerText },
};
