name: "(A) |Î±| Package and Publish Alpha"

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        options:
          - win-x64
          - linux-x64
        default: win-x64
      runtime_artifact_workflow_run_id:
        type: string
        required: true

permissions:
  contents: write

jobs:
  package:
    uses: ./.github/workflows/package.yml
    with:
      platform: win-x64
      runtime_artifact_workflow_run_id: ${{ inputs.runtime_artifact_workflow_run_id }}
    secrets: inherit

  publish:
    needs: package
    uses: ./.github/workflows/publish_alpha.yml
    secrets: inherit
