name: "(A) |Î±| Package and Publish Alpha"

on:
  workflow_dispatch:

jobs:
  package:
    uses: ./.github/workflows/package.yml
    with:
      platform: win-x64
    secrets: inherit

  publish:
    needs: package
    uses: ./.github/workflows/publish_alpha.yml
    with:
      artifact_workflow_run_id: ${{ needs.package.outputs.run_id }}
    secrets: inherit
