# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(A) |Œ±| Publish Alpha"

on:
  workflow_dispatch:
    inputs:
      artifact_workflow_run_id:
        type: string
        required: true
  workflow_call:
    inputs:
      artifact_workflow_run_id:
        type: string

permissions:
  contents: write

run-name: "|Œ±| Publish Alpha"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download artifact
        if: ${{ github.event.inputs.artifact_workflow_run_id }}
        uses: actions/download-artifact@v4
        with:
          name: ${{'noraneko-win-amd64-mar-full'}}
          run-id: ${{inputs.artifact_workflow_run_id}}
          github-token: ${{github.token}}
          path: ~/noraneko-publish

      - name: Try download artifact from same workflow
        if: ${{ !github.event.inputs.artifact_workflow_run_id }}
        uses: actions/download-artifact@v4
        with:
          name: ${{'noraneko-win-amd64-mar-full'}}
          path: ~/noraneko-publish

      - name: Setup
        run: |
          pnpm i

          sudo apt install jq

          node --import @swc-node/register/esm-register ./scripts/update/xml.ts ~/noraneko-publish/meta.json ~/noraneko-publish/WINNT_x86_64-msvc-x64.update.xml

          echo "VERSION=$(cat ~/noraneko-publish/meta.json | jq '.version' | sed 's/"//g')" >> "$GITHUB_ENV"
          echo "NR_VERSION=$(cat ~/noraneko-publish/meta.json | jq '.noraneko_version' | sed 's/"//g')" >> "$GITHUB_ENV"
          echo "ROOT_DIR=$(echo ~)" >> "$GITHUB_ENV"

      - name: Deploy to GitHub Releases üöÄ
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{env.ROOT_DIR}}/noraneko-publish/WINNT_x86_64-msvc-x64.update.xml
            ${{env.ROOT_DIR}}/noraneko-publish/*.mar

          tag_name: "alpha"
          name: "Alpha Release"
          body: |
            "Noraneko Alpha: v${{ env.NR_VERSION }} (Firefox v${{ env.VERSION }})"
          draft: false
          prerelease: true
          token: ${{ github.token }}
      - name: Publish Package üéÅ
        uses: actions/upload-artifact@v4
        with:
          name: noraneko-publish
          path: ~/noraneko-publish/*